application: victory-demo
version: 1
runtime: python27
api_version: 1
threadsafe: yes


skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?\..*
- ^(.*/)?tests/.*
- ^README.md
- ^\.gitignore
- ^\.gitmodules
- ^\.git/.*
- ^\.idea/.*
- ^_images/.*
- ^submodules/bs4/.*
- ^submodules/requests/.*
- ^application/static/binding.py
- ^(.*/)?.*\.coffee
- ^(.*/)?.*\.scss
- ^(.*/)?.*\.rb

handlers:
# icon
- url: /favicon\.ico
  mime_type: image/vnd.microsoft.icon
  static_files: application/static/icon/favicon.ico
  upload: application/static/icon/favicon.ico

# robots.txt
- url: /robots\.txt
  static_files: application/static/robots.txt
  upload: application/static/robots.txt

# CoffeeScript / JavaScript / CSS / image / font
- url: /coffeescript/
  static_dir: application/static/coffeescript
- url: /javascript/
  static_dir: application/static/javascript
- url: /css/
  static_dir: application/static/css
- url: /img/
  static_dir: application/static/img
- url: /font/
  static_dir: application/static/font

# mini profiler
- url: /gae_mini_profiler/static
  static_dir: gae_mini_profiler/static
- url: /gae_mini_profiler/.*
  script: gae_mini_profiler.main.application

# cron jobs
- url: /cron_jobs/.*
  script: cron_jobs.app
  login: admin

- url: /.*
  script: application.app


libraries:
- name: webapp2
  version: "2.5.1"
- name: markupsafe
  version: "latest"
